version: '3'

services:
  redis:
    image: "redis:alpine"
  app:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes: .:/Youtube_Search
    container_name: Youtube_Search
    ports: "8000:8000"
    environment: 
      DATABASE_USER: mongodb_user
      DATABASE_PASSWORD: WIb0aSCWoXXwZL8X
      DATABASE_NAME: Youtube_Search_DB
      DATABASE_URI: mongodb+srv://mongodb_user:WIb0aSCWoXXwZL8X@cluster0.0vrpdwq.mongodb.net/

  celery:
    build: .
    command: celery -A Youtube_Search worker --loglevel=info
    volumes:
      - .:/Youtube_Search
    depends_on: 
      - redis

  celery-beat:
    build: .
      command: celery -A Youtube_Search beat --loglevel=info
      volumes:
        - .:/Youtube_Search
      depends_on: 
        - redis
